
#APPNAME=myappname

PROJECT_ROOT = .

PROJECT_EXCLUSIONS =
PROJECT_OPTIMIZATION_CFLAGS_RELEASE=
PROJECT_OPTIMIZATION_CFLAGS_DEBUG=
PROJECT_DEFINES = 
PROJECT_CFLAGS = 

PROJECT_LDFLAGS=-Wl,-rpath=./libs


PROJECT_EXTERNAL_SOURCE_PATHS = /usr/include/luajit-2.1

PROJECT_LDFLAGS+=-lluajit-5.1

